# Generated by Django 2.0rc1 on 2017-12-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='company',
            new_name='employer',
        ),
    ]
